# Copyright (c) 2016-2021 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

name: Build and Test

on: [push, pull_request]

# on:
#   release:
#     types: [created]

jobs:
  generate-matrix:
    name: Generate Job Matrix
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate Job Matrix
        id: set-matrix
        env:
          MATRIX: '{"config": [{"name": "Linux NodeJS 15","nodejs_version": "15","os": "ubuntu-20.04","os_kind": "linux"},
                               {"name": "Linux NodeJS 14","nodejs_version": "14","os": "ubuntu-20.04","os_kind": "linux"},
                               {"name": "Linux NodeJS 12","nodejs_version": "12","os": "ubuntu-20.04","os_kind": "linux"},
                               {"name": "macOS NodeJS 15","nodejs_version": "15","os": "macos-10.15","os_kind": "macos"},
                               {"name": "macOS NodeJS 14","nodejs_version": "14","os": "macos-10.15","os_kind": "macos"},
                               {"name": "macOS NodeJS 12","nodejs_version": "12","os": "macos-10.15","os_kind": "macos"},
                               {"name": "Windows NodeJS 15","nodejs_version": "15","os": "windows-2019","os_kind": "windows"},
                               {"name": "Windows NodeJS 14","nodejs_version": "14","os": "windows-2019","os_kind": "windows"},
                               {"name": "Windows NodeJS 12","nodejs_version": "12","os": "windows-2019","os_kind": "windows"},
                               ]}'
        run: |
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"

  builds:
    needs: generate-matrix
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    name: Build and Test ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.config.nodejs_version }}
      - run: npm install
      - run: git status
      - run: git diff
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    if: ${{ matrix.config.os_kind == 'linux' }}
    name: Public NPM ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.config.nodejs_version }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  # publish-gpr:
  #   needs: builds
  #   runs-on: ${{ matrix.config.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.config.nodejs_version }}
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NODE_PRE_GYP_GITHUB_TOKEN}}

